import './js/header';
import './js/hero';
import './js/dessert-list';
import './js/about-us';
import './js/feedback';
import './js/faq';
import './js/footer';
import './js/dessert-details-modal';
import './js/order-modal';
